apiVersion: v1
clusters:
- cluster:
    server: https://160.44.204.91:6443
    certificate-authority: ./ca.pem
  name: api 
contexts:
- context: 
    namespace: kube-system
    user: namespaceuser
    cluster: api
  name: api
current-context: api
kind: Config
preferences: {}
users:
- name: namespaceuser
  user:
    client-certificate: ./cluster-admin.pem
    client-key: ./cluster-admin-key.pem

